name: forms_example
description: Example app for the Forms package
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  forms:
    path: ../
  forms_annotations:
    path: ../packages/forms_annotations
  models_ns:
    path: ../../models_ns

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
