targets:
  $default:
    builders:
      forms_generator:forms_generator:
        enabled: true

builders:
  forms_generator:
    import: "package:forms_generator/forms_generator.dart"
    builder_factories: ["formBuilder"]
    build_extensions: {".dart": [".forms_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
