name: forms_generator
description: Генератор кода для типизированных форм
version: 0.1.0
homepage:
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  forms_annotations:
    path: ../forms_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
