name: alogrithms
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  models_ns:
    path: ../models_ns
  
  forms:
    path: ../forms 
  forms_annotations:
    path: ../forms/packages/forms_annotations
  
  figure_io:
    path: ../figure_io

  algorithm_interface:
    path: ./packages/algorithm_interface

  # Перечисление конкретных алгоритмов
  lab_01_common:
    path: ./packages/lab_01/lab_01_common
  lab_01_27:
    path: ./packages/lab_01/lab_01_27
  lab_01_40:
    path: ./packages/lab_01/lab_01_40
  lab_01_41:
    path: ./packages/lab_01/lab_01_41  
  lab_01_42:
    path: ./packages/lab_01/lab_01_42  
  lab_01_43:
    path: ./packages/lab_01/lab_01_43  
  lab_01_44:
    path: ./packages/lab_01/lab_01_44
  lab_01_45:
    path: ./packages/lab_01/lab_01_45  
  lab_01_46:
    path: ./packages/lab_01/lab_01_46  
  lab_01_47:
    path: ./packages/lab_01/lab_01_47  
  lab_01_48:
    path: ./packages/lab_01/lab_01_48  
  lab_01_49:
    path: ./packages/lab_01/lab_01_49 
  lab_01_50:
    path: ./packages/lab_01/lab_01_50  
  lab_01_51:
    path: ./packages/lab_01/lab_01_51  
  lab_01_52:
    path: ./packages/lab_01/lab_01_52  
  lab_01_53:
    path: ./packages/lab_01/lab_01_53  
  lab_01_54:
    path: ./packages/lab_01/lab_01_54  
  lab_01_55:
    path: ./packages/lab_01/lab_01_55  
  lab_01_56:
    path: ./packages/lab_01/lab_01_56
  rxdart: ^0.28.0
  models_data_ns: 
    path: ./packages/models_data_ns

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  forms_generator:
    path: ../forms/packages/forms_generator
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
