name: forms_annotations
description: Аннотации для генерации типизированных форм
version: 0.1.0
homepage:
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
